### ISSUE TITLE
How to add custom operators 

### ISSUE THREAD

**Issue by aman123shi** [c-w/mathquill4quill#93] opened 2023-02-22 05:56 UTC
i have described  the problem here https://stackoverflow.com/questions/75525816/how-to-write-the-second-value-of-custom-operators-array-in-mathquill-editor

**Comment by c-w** [comment] 2023-02-22 07:59
There's two parts to an operator button: the LaTeX that gets shown on the button and the content that gets inserted into the editor when the button is clicked. Let's take an example operator button definition like `["\\pi", "3.14"]`. This will render the symbol π on the button and when the button is clicked will insert "3.14" into the editor.

**Comment by aman123shi** [comment] 2023-02-22 11:44
i want to insert  a placeholder of characters that are displayed on the button to be inserted on the editor then i can edit it 
for example  i have  this 2 x 2 matrix Latex  **[String.raw`\begin{bmatrix}a & b \\c & d \end{bmatrix}`, 'what to put here']** this will display matrix on the button but don't know what to put for the second value

**Comment by c-w** [comment] 2023-02-22 13:32
What approaches have you tried?

**Comment by aman123shi** [comment] 2023-02-22 18:06
for eg this Logarithm  LaTex will give me a log symbol with editable a and b values for the second  value of the array i just copied the latex value and remove a and b from the curly braces and it worked.   ["\\log_{a}{b}", "\\log_{}{}"]  i just want to know if there is a general rule that i can use for other Latex values this approach worked for some Latex values but didn't work for others

**Comment by c-w** [comment] 2023-02-22 20:31
Could you provide some examples where your approach failed?

**Comment by aman123shi** [comment] 2023-02-23 05:47
**[ String.raw`\begin{bmatrix}a & b \\c & d \end{bmatrix}`, String.raw`\begin{bmatrix}{} & {} \\{} & {} \end{bmatrix}`,],**  this 2x2 matrix latex will render on the Button but when i click it , it won't give me Editable Matrix on the editor it's just blank. but the above Logarithm latex will give me editable log symbol with a and b value then i will substitute with my value and hit save i get my log symbol with my values on the editor

**Comment by c-w** [comment] 2023-02-23 08:05
Matrices specifically aren't supported by MathQuill which is used to render the formulae in the editor. See https://github.com/c-w/mathquill4quill/issues/52 for additional detail.

Resolving this issue since the problem is a limitation of an upstream dependency and not of mathquill4quill itself. Feel free to re-open if you have any additional questions or concerns.

**Closed by c-w** 2023-02-23 08:05 UTC
Labels: question
