### ISSUE TITLE
Formula input appears twice

### ISSUE THREAD

**Issue by vieyama** [c-w/mathquill4quill#92] opened 2023-02-15 03:09 UTC
hi, thank you for creating this awesome library. but i have some problem when use this library. when i installed it on nextjs the formula's input appears twice. can you help me please? thanks.

![image](https://user-images.githubusercontent.com/25025446/218916200-418aa51b-917e-4702-9d90-c84a8d171fdb.png)

this is my dependencies:

> "@edtr-io/mathquill": "^0.11.0",
    "jquery": "3.6.1",
    "katex": "0.16.2",
    "mathquill4quill": "^2.4.0",
    "react-quill": "^2.0.0"

**Comment by c-w** [comment] 2023-02-15 13:28
Thanks for reaching out. I just [published](https://justamouse.com/mathquill4quill/nextjs/) the nextjs [demo code](https://github.com/c-w/mathquill4quill/tree/5e49f20c769c316359657f8a700f81bb29f293ef/nextjs) which is included in this repository and can't reproduce the behavior. Could you take a look at the demo and verify that your setup is similar.

**Comment by vieyama** [comment] 2023-02-16 03:27
thankyou for your response.

https://replit.com/@Yovie-Fesya-Fes/Text-Editor-Quill?v=1

that is my replit code. im using the same code with the demo next js in your repo

**Comment by c-w** [comment] 2023-02-16 09:32
The issue is your use of strict mode which runs the componentDidMount twice. If you need to have strict mode enabled, I documented a work-around for this issue in f96f4ab.

**Comment by c-w** [comment] 2023-02-16 10:49
Resolving, feel free to reopen if you have any further questions or concerns.

**Closed by c-w** 2023-02-16 10:49 UTC

**Comment by vieyama** [comment] 2023-02-16 11:59
it solved with changing the componentdidmount code. thankyou very much
